### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'pretrained_cifar10.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by ZhaoYibo61** [tarujg/keras-deep-compression#1]
Hello, I found such an error message during the experiment, "OSError: Unable to open file (unable to open file: name = 'pretrained_cifar10.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)". How can I solve it, thank you!
![QQ截图20200724195052](https://user-images.githubusercontent.com/62468648/88388608-6d1d5600-cde7-11ea-94b2-d31a79f36c01.png)

**Comment by ZhaoYibo61** [comment]
This is my email: zhaoyibo@hnu.edu.cn

**Comment by tarujg** [comment]
@ZhaoYibo61 I have uploaded the *.h5 files in the latest commit.

**Comment by ZhaoYibo61** [comment]
Thanks!
&nbsp;




赵一博
学生
河南大学


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Taruj Goyal"<notifications@github.com&gt;; 
发送时间: 2020年7月26日(星期天) 上午9:45
收件人: "tarujg/keras-deep-compression"<keras-deep-compression@noreply.github.com&gt;; 
抄送: "一个努力吃胖的小瘦子"<1391619705@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tarujg/keras-deep-compression] OSError: Unable to open file (unable to open file: name = &#39;pretrained_cifar10.h5&#39;, errno = 2, error message = &#39;No such file or directory&#39;, flags = 0, o_flags = 0) (#1)





 
@ZhaoYibo61 I have uploaded the *.h5 files in the latest commit.
