### ISSUE TITLE
Tucker ranks

### ISSUE THREAD

**Issue by ZhaoYibo61** [tarujg/keras-deep-compression#2]
Hello, have you tried using VBMF(Variational Bayes Matrix Factorization) to set Tucker rank instead of setting it manually? If so, how was it achieved? Thanks!
This is my email: zhaoyibo@hnu.edu.cn

**Comment by tarujg** [comment]
@ZhaoYibo61 I haven't implemented VBMF for the project. You can, however, view the following, [link](https://github.com/CasvandenBogaard/VBMF/blob/master/VBMF.py) for reference.

**Comment by ZhaoYibo61** [comment]
> @ZhaoYibo61 I haven't implemented VBMF for the project. You can, however, view the following, [link](https://github.com/CasvandenBogaard/VBMF/blob/master/VBMF.py) for reference.

Thanks!
